.python_pylint:
  image: python:${IMAGE_TAG}
  stage: lint
  variables:
    IMAGE_TAG: 3.13
    PYLINT_OPTIONS: ""
    PYLINT_OUTPUT: "report_pylint.xml"
    PYLINT_EXIT_ZERO: "true"
  before_script:
  script:
    - |
        set -x
        cd "${PROJECT_ROOT}"
        echo "+ install dependencies"
        pip install pylint pylint_junit
        echo "+ lint"
        options="--output-format=pylint_junit.JUnitReporter --output=$PYLINT_OUTPUT"
        $([ ${PYLINT_EXIT_ZERO} == "true" ]) && options="${options} --exit-zero"
        pylint ${options} $PYLINT_OPTIONS $(find -type f -name "*.py" ! -path "**/.venv/**")
  artifacts:
      when: always
      paths:
        - ${PROJECT_ROOT}/${PYLINT_OUTPUT}
      reports:
        junit: ${PROJECT_ROOT}/${PYLINT_OUTPUT}
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /root/.cache/pip
