stages:
  - lint
  - build
  - test
  - release
  - review
  # - deploy

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  GIT_DEPTH: 10
  GIT_USER_EMAIL: "gitlab@example.com"
  GIT_USER_NAME: "gitlab-CI"
  BASE_DOMAIN: wmars.party

image: python:3.13

include:
  - local: ".gitlab-ci/actions/**.yaml"
  - local: ".gitlab-ci/workflows/**.yaml"
