{{- if .Values.conduit.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "back.fullname" . }}-migrations
  labels:
    {{- include "back.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "back.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "back.fullname" . }}
            - secretRef:
                name: {{ include "back.fullname" . }}
          command:
            - /bin/bash
            - -c
            - |
                set -eu -o pipefail
                alembic upgrade head
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
{{- end }}
