ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: back.example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: back-tls
      hosts:
        - back.example.local
