apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "back.fullname" . }}
  labels:
    {{- include "back.labels" . | nindent 4 }}
data:
  CONDUIT_POSTGRES_DB: {{ .Values.conduit.postgresDb | quote }}
  CONDUIT_POSTGRES_HOST: {{ .Values.conduit.postgresHost | quote }}
  CONDUIT_POSTGRES_PORT: {{ .Values.conduit.postgresPort | quote }}
  ALEMBIC_CONFIG: {{ .Values.conduit.migrations.alembicConfig | quote }}
