apiVersion: v1
kind: Secret
metadata:
  name: {{ include "back.fullname" . }}
  labels:
    {{- include "back.labels" . | nindent 4 }}
data:
  CONDUIT_SECRET_KEY: {{ .Values.conduit.secretKey | b64enc }}
  CONDUIT_POSTGRES_USER: {{ .Values.conduit.postgresUser | b64enc }}
  CONDUIT_POSTGRES_PASSWORD: {{ .Values.conduit.postgresPassword | b64enc }}
